### PR TITLE
Fixing calling modules bug and auto get x,y,z coordinates

### PR DESCRIPTION
**Pull request by ElPilouchador**
Fix bug when trying to import the modules because they are not called with the correct names.

Please be sure of the names on your local side; name them as on github for faster and easier debug.

Now the robot automatically get his coordinates.

### CODE REVIEW

**Comment by Nicolas62x** [comment]
Sorry it wont work did you test it ?
The point of the locals coord is to remove nav upgrade because the nav upgrade can’t tell coordinates properly, it tells locals coordz compare to the center of the map used to craft it

**Review by Nicolas62x — COMMENTED** [review]
I agree only for the name of the modules

**Comment by ElPilouchador** [comment]
Ok
thanks a lot for the explanation.
I will delete this PR and submit a new one with only file names

**Comment by Nicolas62x** [comment]
Np

**Pull request closed without merging**
