### PR TITLE
ADD: chaos detection + bugfix

### PR DESCRIPTION
**Pull request by Nicolas62x**
image

### CODE REVIEW

**Comment by Fuzay** [comment]
How do you check for chaos guardian ?

**Comment by Nicolas62x** [comment]
I’m checking if the first healer is alive if not i asume that there is no island (it has exploded after the death of the chaos)

**Comment by Nicolas62x** [comment]
That may be a problem, the explosion, will the bot be faster than the explosion ?

**Comment by ElPilouchador** [comment]
Thanks to the wiki, the island will collapse 35 seconds after breaking the chaos crystal.

 Maybe the robot could place an block breaker, a vacuum hopper, an ender chest and an redstone wireless receiver (the block that emit redstone signal on certain channel).

 The robot go 1000 blocks away place an other wireless receiver wich as the effect to trigger the block breaker and break the crystal,  pick up the shards with the vacuum hopper and put them in an ender chest.
That may be a solution to the fast explosion.
Hope it will help.

**Comment by Nicolas62x** [comment]
Oh but the bot may be fast enough if he goes down, the explosion stop not that far down

**Comment by Fuzay** [comment]
Yep, we'll have to check that. The vacum hopper method would also work but it would mean that the robot would need to be constantly refilled which would be annoying.

**Comment by Kreoz42** [comment]
The filling time is long?

**Comment by Nicolas62x** [comment]
image

i was right he can go low enough to survive you just need to pre dig the way down i'll make a function for that

**Pull request merged**
